### ISSUE TITLE
Array allocation in calc_seasonality2 function

### ISSUE THREAD

**Issue by allayur** [TillF/WASA-SED#81]
I am running the tutorial example with a code compiled with gfortran on Ubuntu. When the function calc_seasonality2 is called with different size (e g c_season after rainy_season) then allocation of a new array size does not work correctly. Specifically the error is 
Fortran runtime error: Dimension 1 of array 'calc_seasonality2' has extent 59 instead of 11
I tried to make this array allocatable but that produced another error

**Comment by TillF** [comment]
Thanks for reporting your observations. Please confirm if you used the latest version of the model.
We will try to look into the subject as soon as we find the time.

**Comment by allayur** [comment]
Thank you. This issue is fixed. However, to proceed we would be graful to get an example of soil.dat and vegetation.dat as input for lumpR. We have examples in WASA package, but the order, the structure of the files and names are as lumpR output, not input so it is a bit difficult to sort thing out. And I am glad to inform we published a paper with lumpR https://doi.org/10.1016/j.catena.2020.105109

**Comment by tpilz** [comment]
Hi, glad to see that you found lumpR useful for your analyses and published a paper with it.

The lumpR output should produce soil.dat and vegetation.dat ready for use within WASA. Otherwise both files are also described in the [online manual](https://tillf.github.io/WASA-SED/#3-2-input-files-for-the-hillslope-module). So, where exactly did you run into problems?

[Here](https://github.com/tpilz/paper_drought_prediction_brazil/blob/master/experiments/wasa_calibration/wasa_setups_calibrated.tar.gz) you can also find the setup (i.e. 5 independent setups for several sub-catchments) that I used for a study in Brazil. These should run right away (although I haven't tested it with the latest version of WASA).

**Comment by TillF** [comment]
I close this issue now. For requests concerning lumpR please use its own repository https://github.com/tpilz/lumpR/ for submitting issues.
